### ISSUE TITLE
COCOPretrained models missing

### ISSUE THREAD

**Issue by hafizas101** [alnfedorov/traffic-analysis#1]
Hi..
Hi. I tried to run your code on other complex datasets like UA-DETRAC dataset and videos. When I tried to run the code 'predict_video.py', it asks for a **'COCOPretrained'** folder containing **.pth** files. Can you please provide this folder ? Attached file 'models.png' shows the error.
![models](https://user-images.githubusercontent.com/44812167/67590318-692eab80-f763-11e9-8491-af34bd3b96a6.png)

**Comment by alnfedorov** [comment]
Hello!
Sorry for the delayed replay. As stated in the readme, the primary purpose of this repository is to serve as a reference for model implementation-training details. We decided not to go further for several reasons: trained model size is too large and cannot be stored on the github, Detectron architecture is not really extensible for new datasets. Nevertheless, our main concern was licensed based: we wanted to keep MIT license, while SORT has viral GPL v3.0. I think, it is worth to provide a link to our best pre-trained model, an additional GPL v3.0 branch with SORT included, and small instruction on how to run the model and visualize predicts. Will it be sufficient for you?

However, I would not expect much from this idea. Target domains are really distinct in this case.

**Comment by alnfedorov** [comment]
I think, the repo will be updated within 1-2 weeks. I am a bit busy with new projects right now.

**Comment by hafizas101** [comment]
yes. That will be great. Upload COCOPretrained folder on Google drive etc. and provide the link.

Thank you very much.

**Comment by hafizas101** [comment]
Hi Alexander..
Any update on this issue by this weekend please ?

**Comment by alnfedorov** [comment]
Hi!
I will try to find enough time, but no promises. Anyway, I will finish until the mid-November.

**Comment by alnfedorov** [comment]
@hafizas101 done.

**Comment by hafizas101** [comment]
@alnfedorov 
Thank you very much Alexander. Today I finally managed to run this code successfully on Colab because I was having problems with pytorch version, cuda version etc. Once again thank you very much.
