### ISSUE TITLE
Please upload cross-road-regions.png

### ISSUE THREAD

**Issue by rambel123** [alnfedorov/traffic-analysis#2]
Hi,
Please upload cross-road-regions.png in gdrive
Thank you

**Comment by alnfedorov** [comment]
Done. Please, check.

**Comment by thijsbrouwers** [comment]
I cannot find in the two links in the README. Can you give a link to the upload, please?

**Comment by alnfedorov** [comment]
@thijsbrouwers Link in the last paragraph of the README: https://drive.google.com/file/d/1sQ1lnEw8ZYcwA8U_fKsbpIyqRfJTy-Rq/view?usp=sharing.  

cross-road-regions.png file should be in the archive.

**Comment by thijsbrouwers** [comment]
@alnfedorov it's not in there.. Only the checkpoint and mp4 file

**Comment by alnfedorov** [comment]
@thijsbrouwers Please, make sure that you use the up-to-date link. It should be inside.  

In any case, here it is: ![cross-road-regions](https://user-images.githubusercontent.com/18511496/72012816-aa682f00-326d-11ea-98c8-fe3d9be28917.png)  

Yet, I am not sure that this file will work - github might use lossy compression. So, it is better to use gdrive archive.
