### ISSUE TITLE
image id in your json file

### ISSUE THREAD

**Issue by xingchenzhang** [alnfedorov/traffic-analysis#5]
Hi,

Thank you very much for providing your code! Nice work!

I have a question about your data, could you please help to clarify?

Basically, I have checked your jason file for training data and val data. In the json file, you have image id, for example "914". However, you do not have an image named 914, but you have "id-914-22.png". I am wondering does the image id "914" refer to "id-914-22.png"? Do I need to change "id-914-22.png" to "914.png"?

Looking forward to your reply.

Thanks again!
Xingchen

**Comment by alnfedorov** [comment]
Hi,

Please, check the meta.json file. It is a valid COCO annotation file, and for each image, it includes the following data:
```{"id": 106, "width": 1920, "height": 1080, "file_name": "id-399-080.png"}```

As you may see, we can get here a valid **id** here as well as **file_name**.

All in all, simply trust meta.json files. Feel free to reopen the issue if you still have questions.

**Comment by xingchenzhang** [comment]
> Hi,
> 
> Please, check the meta.json file. It is a valid COCO annotation file, and for each image, it includes the following data:
> `{"id": 106, "width": 1920, "height": 1080, "file_name": "id-399-080.png"}`
> 
> As you may see, we can get here a valid **id** here as well as **file_name**.
> 
> All in all, simply trust meta.json files. Feel free to reopen the issue if you still have questions.

Thank you very much for your reply! Yes, I just double checked and I have seen the 'file_name'.

Thanks!
